# Generated by Django 2.2.28 on 2023-07-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Home/icon/images/'),
        ),
    ]
