# Generated by Django 2.2.28 on 2023-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_home_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('map', models.ImageField(upload_to='Country/map/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='icon',
        ),
    ]
