# Generated by Django 2.2.28 on 2023-07-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230721_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Test/photo/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='reads',
            name='front_page',
        ),
    ]
